name: care
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python==3.12
  - tifffile
  - pillow
  - opencv
  - jupyterlab
  - mlflow==2.22.0
  - natsort
  - onnx==1.17.0
  - scikit-image
  - seaborn
  - pip:
      - onnxruntime-gpu==1.22.0
      - nvidia-cublas-cu12==12.5.3.2
      - nvidia-cuda-cupti-cu12==12.5.82
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.5.82
      - nvidia-cuda-runtime-cu12==12.5.82
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.3.61
      - nvidia-curand-cu12==10.3.6.82
      - nvidia-cusolver-cu12==11.6.3.83
      - nvidia-cusparse-cu12==12.5.1.3
      - matlabengine==24.2.2
